"""make_school_id_nullable

Revision ID: a5295f2ca004
Revises: b1c2d3e4f5a6
Create Date: 2026-06-21 04:59:02.236315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5295f2ca004'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_students_supabase_user_id'), table_name='students')
    op.create_unique_constraint(None, 'students', ['supabase_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.create_index(op.f('ix_students_supabase_user_id'), 'students', ['supabase_user_id'], unique=True)
    op.alter_column('students', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
