"""add_display_name_to_students

Revision ID: a9493668adde
Revises: fa23dac1a91b
Create Date: 2026-06-20 20:38:56.896520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9493668adde'
down_revision: Union[str, None] = 'fa23dac1a91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'display_name')
    # ### end Alembic commands ###
